baseURL = 'https://hugo-theme-nano.netlify.app/'
languageCode = 'en-us'
title = 'Nano theme'
theme = 'hugo-theme-nano'

[params]
description = 'slightly a billionth of a theme'
color = 'azure'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
